# Generated by Django 5.0.6 on 2024-07-12 14:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SliderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(blank=True)),
                ('descriptions', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='slider/')),
                ('button_one', models.URLField()),
                ('button_two', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slider_item', models.ManyToManyField(to='homehero.slideritem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
