# Generated by Django 5.0.6 on 2024-07-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homehero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('buton_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('about_item', models.ManyToManyField(to='homehero.about_item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
