# Generated by Django 5.0.6 on 2024-07-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homehero', '0002_about_item_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_item',
            name='type',
            field=models.CharField(blank=True, choices=[('services', 'services'), ('About', 'About')], max_length=40),
        ),
    ]
