# Generated by Django 5.0.6 on 2024-07-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homehero', '0004_alter_about_item_buton_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('about_item', models.ManyToManyField(to='homehero.about_item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
