# Generated by Django 5.0.6 on 2024-07-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homehero', '0005_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heart_Transplants', models.IntegerField(default=0)),
                ('BARIATRIC_SURGERY', models.IntegerField(default=0)),
                ('CRITICAL_CARE', models.IntegerField(default=0)),
                ('EXPERT_Doctor', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
