# Generated by Django 5.0.6 on 2024-07-26 14:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=400)),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
                ('blog_desc', models.TextField()),
                ('blog_img', models.ImageField(upload_to='blog/')),
                ('poyam_text', ckeditor.fields.RichTextField(blank=True)),
                ('blog_Writer_name', models.CharField(max_length=50)),
                ('blog_Writer_desc', models.TextField()),
                ('blog_Writer_img', models.ImageField(upload_to='writer_img/')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AllBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('blog_item', models.ManyToManyField(to='blog.blogss')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
