# Generated by Django 5.0.6 on 2024-07-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogss',
            name='blog_Writer_fb_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='blogss',
            name='blog_Writer_linkdin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='blogss',
            name='blog_Writer_twiter_url',
            field=models.URLField(blank=True),
        ),
    ]
