# Generated by Django 5.0.6 on 2024-07-25 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Protfolio',
            new_name='Protfolios',
        ),
    ]
