# Generated by Django 5.0.6 on 2024-07-17 07:53

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Dr_Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_name', models.CharField(max_length=39)),
            ],
        ),
        migrations.CreateModel(
            name='Drs_socaials_medias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_name', models.CharField(max_length=40)),
                ('social_name', models.CharField(max_length=40)),
                ('social_icon', models.CharField(max_length=30)),
                ('social_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Education_Medical_Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Medical_Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Opening_Hour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_name', models.CharField(blank=True, max_length=40)),
                ('day_name', models.CharField(blank=True, max_length=40)),
                ('day_opening', models.CharField(blank=True, max_length=20)),
                ('day_closing', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Percentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_name', models.CharField(blank=True, max_length=150)),
                ('name_of_percentage', models.CharField(blank=True, max_length=60)),
                ('rate_of_percentage', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Dr_Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_name', models.CharField(max_length=39)),
                ('certifications', models.ManyToManyField(to='doctor.certification')),
            ],
        ),
        migrations.CreateModel(
            name='Dr_Education_Medical_Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_name', models.CharField(max_length=39)),
                ('trainings', models.ManyToManyField(to='doctor.education_medical_training')),
            ],
        ),
        migrations.CreateModel(
            name='Dr_Medical_Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_name', models.CharField(max_length=39)),
                ('specializations', models.ManyToManyField(to='doctor.medical_specialization')),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_name', models.CharField(max_length=60)),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
                ('profession_name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='images/')),
                ('desc', ckeditor.fields.RichTextField(blank=True)),
                ('phone_number', models.CharField(max_length=18)),
                ('job_place', models.CharField(max_length=500)),
                ('fax_number', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('web_app_link', models.URLField(blank=True)),
                ('certifications', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='doctor.dr_certification')),
                ('education_trainings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='doctor.dr_education_medical_training')),
                ('medical_specializations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='doctor.dr_medical_specialization')),
                ('trainings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='doctor.dr_training')),
                ('social_media', models.ManyToManyField(blank=True, to='doctor.drs_socaials_medias')),
                ('opening_hours', models.ManyToManyField(related_name='doctors', to='doctor.opening_hour')),
                ('professional_rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='doctor.percentage')),
            ],
        ),
        migrations.AddField(
            model_name='dr_training',
            name='trainings',
            field=models.ManyToManyField(to='doctor.training'),
        ),
    ]
