# Generated by Django 5.0.6 on 2024-07-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='professional_rating',
        ),
        migrations.AddField(
            model_name='doctors',
            name='professional_rating',
            field=models.ManyToManyField(related_name='doctors', to='doctor.percentage'),
        ),
    ]
