# Generated by Django 5.0.6 on 2024-08-01 10:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investigations_fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(blank=True, max_length=40)),
                ('investigations_name', models.CharField(blank=True, max_length=40)),
                ('investigations_fee', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Opening_Hour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(blank=True, max_length=40)),
                ('day_name', models.CharField(blank=True, max_length=40)),
                ('day_opening', models.CharField(blank=True, max_length=20)),
                ('day_closing', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Treatments_fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(blank=True, max_length=40)),
                ('treatments_name', models.CharField(blank=True, max_length=40)),
                ('treatments_fee', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_img', models.ImageField(upload_to='deptImg/')),
                ('dept_name', models.CharField(choices=[('Cardiologists', 'Cardiologists'), ('Orthopaedics', 'Orthopaedics'), ('Gastroenterology', 'Gastroenterology'), ('Neurosciences', 'Neurosciences'), ('Spine', 'Spine'), ('Cancer', 'Cancer'), ('Colorectal', 'Colorectal'), ('Bariatric', 'Bariatric')], max_length=100)),
                ('dept_desc', ckeditor.fields.RichTextField(blank=True)),
                ('investigations_fee', models.ManyToManyField(to='department.investigations_fee')),
                ('opening_hour', models.ManyToManyField(to='department.opening_hour')),
                ('treatments_fee', models.ManyToManyField(to='department.treatments_fee')),
            ],
        ),
    ]
